name: wanakanm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  file_picker: ^8.1.4
  path_provider: ^2.1.2
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  home_widget: ^0.7.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  archive: ^3.6.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.1
  flutter_displaymode: ^0.6.0
  http: ^1.2.1 # For making API calls (if not using a dedicated SDK)
  google_generative_ai: ^0.4.7
  syncfusion_flutter_pdf: 29.1.40
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/logo.png
    - assets/icons/shadman.jpg
    
  fonts:
    - family: Nrt_bold
      fonts:
        - asset: assets/Fonts/Nrt_bold.ttf
    - family: Nrt_regular
      fonts:
        - asset: assets/Fonts/Nrt_regular.ttf
    - family: K24
      fonts:
        - asset: assets/Fonts/k24.ttf
    - family: Speda
      fonts:
        - asset: assets/Fonts/speda.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true

